### PR TITLE
Remove Nintendo 3DS and Wii U entries from game console adblock list

### PR DESCRIPTION
**Pull request by MisterSheeple**
Online services for 3DS and Wii U have ceased to exist as of a few weeks ago, so there's pretty much no point in having these anymore.

### CODE REVIEW

**Comment by DandelionSprout** [comment]
I'll get around to remove the 3DS entry, as it's extremely unlikely that new themes would be added to the 3DS Theme Shop that'd result in the pink circle.

The Wii U one I have to crosscheck. I need to compare the loading times of Wii Sports Club's initial loading times again, to see if they still differ post-"Nintendo Network" shutdown.

**Comment by DandelionSprout** [comment]
Good news: You do not need to do the "Resolve conflicts" button above.

Less good news: I temporarily forgot that I'm waiting for a new Wii U power supply from eBay Germany, as the previous one that had lasted 12 years had a wire slightly exposed due to swirling around with a nearby speaker cable, and after around 2.5cm got exposed, I presumed electrician tape wasn't going to work long-term, unfortunately.

**Comment by MisterSheeple** [comment]
The thing is there are actually third party Miiverse clients that exist now and depend on that endpoint for Wii U. And doesn't Wii Sports Club have Miiverse functionality in it?

**Comment by DandelionSprout** [comment]
Do you happen to have any links for any third-party clients that have been able to operate for some time without collapsing or shutting down themselves?

**Comment by MisterSheeple** [comment]
> Do you happen to have any links for any third-party clients that have been able to operate for some time without collapsing or shutting down themselves?

A project called Pretendo has a Miiverse client called Juxaposition (more info here: https://pretendo.network/docs/install/juxt).

There's another one called Rverse, but I don't think they have a website.

**Comment by MisterSheeple** [comment]
In 27f09b2c809b413201737d5997f7b6bcc124c0ac I can see that you seem a bit confused about how Pretendo works. Their public documentation for how Nintendo's endpoints work is basically inexistent, but basically that one is used for sending the client a list of Miiverse servers. Juxtaposition is one of the services Pretendo hosts for Wii U/3DS. They also do online servers for various games, but this endpoint only concerns Miiverse. I don't know if this is how Rverse does it, but Juxt essentially uses DNS to spoof that domain and load their own custom Miiverse servers. This is why it's not really ideal for it to be blocked. On top of that, Wii Sports Club has Miiverse functionality in it, so blocking a feature with legitimate use cases just to save a few seconds of loading time doesn't make much sense to me.

**Comment by DandelionSprout** [comment]
I've got experience with RiiConnect24 and Wiimmfi to some extent, I just felt it was pretty odd that the Juxt page on Pretendo's wiki claimed Pretendo was in closed beta, which cannot possibly be the case when checking through their websites' main pages as well as YouTube reviewers.

My new Wii U charger I expect to arrive on Wednesday at latest (though there's been fluctuations at times), and then I'd need to change my softmod from Haxchi to one of the other 2 or more options that are recommended nowadays.

**Comment by DandelionSprout** [comment]
After I had wrapped my previous PSU in ungodly amounts of electrician tape, it seems you were right, in the sense that there's no time saving at all with that entry anymore. Once Wii Sports Club itself had concluded "This service has been discontinued", its connection error screen comes up within 1.5sec, regardless of connection.

(Back in around 2019, the margin had been around 11 seconds without the entry due to it trying to connect to Miiverse and failing, contra around 5sec with the entry.)

**Pull request closed without merging**
