### PR TITLE
missing characters

### PR DESCRIPTION
**Pull request by yokoffing**
Showing as invalid in uBlock Origin.

Please double-check my corrections and alter if need be, of course.

### CODE REVIEW

**Comment by DandelionSprout** [comment]
The proposed changes would turn a *complete* 180° on which devices the entries would apply to (e.g. mobile v desktop; uBO v non-uBO), and would be a pretty bad idea to merge verbatim.

I guess I'll see if I have time to test out the uBO beta builds again later this week nevertheless.

**Comment by yokoffing** [comment]
Yeah. I was just marking them on the fly while I was at my university. But those lines do need to be look over in uBO.

**Comment by DandelionSprout** [comment]
Okay, so having now tested in 1.44.5b14, I don't really think those were missing characters. Instead I think https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#if-condition will explain most of the factors that have happened here.

After all, some entries simply either are superfluous in uBlock Origin / desktop browsers; or could possibly even break sites sometimes.

**Comment by yokoffing** [comment]
Thanks for checking! I’ll look into why this was showing invalid on my side.

**Pull request closed without merging**
