### PR TITLE
Update LegitimateURLShortener.txt

### PR DESCRIPTION
**Pull request by Nojuuu**
Stuck in infinite loading when you try to open article on mobile.

### CODE REVIEW

**Comment by Nojuuu** [comment]
Also since removing these usually doesn't cause any issues on desktop, could maybe do something like?

```adblock
!#if !env_mobile
$removeparam=/^amp$/
$removeparam=/^amp=true$/
$removeparam=/^amp=1$/
!#endif

!#if env_mobile
$removeparam=/^amp$/,domain=~eurasiantimes.com
$removeparam=/^amp=true$/
$removeparam=/^amp=1$/,domain=~listafriikki.com
!#endif
```

**Comment by DandelionSprout** [comment]
I ran on the assumption that AMP pages were considered strongly undesirable among most uBO users and privacy fans, and that entries that had the side-effect of forcing non-AMP pages were desirable.

I'll strongly consider the first code paragraph from your 2nd comment above after making some dinner.

**Comment by DandelionSprout** [comment]
After thinking about it and realising *"Wait, would desktop versions of websites at any point in time have `?amp` at the end?"*, I'll merge this PR as-is after all instead.

**Comment by Nojuuu** [comment]
> After thinking about it and realising _"Wait, would desktop versions of websites at any point in time have `?amp` at the end?"_, 

Usually only if somebody sends you link that has the parameter already.

**Pull request merged**
