### PR TITLE
Add discord.gift as denyallow modifier

### PR DESCRIPTION
**Pull request by KnightmareVIIVIIXC**
Remove @@||discord.gift^ and change to ||discord*.gift^$denyallow=discord.gift. Tested and working.

### CODE REVIEW

**Comment by iam-py-test** [comment]
The AdGuard Home version is generated from https://github.com/DandelionSprout/adfilt/blob/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt
So it should be changed to `||discord*.gift^$all,~inline-font,domain=~discord.gift` in that version.
I am going to hold off on making that change because maybe Imre has a reason why he is going it this way.
Thanks

**Comment by DandelionSprout** [comment]
I see no real problem with `@@||discord.gift^`. Is there any particular reason why the proposed entry would be more useful?

**Comment by DandelionSprout** [comment]
Okay, I see now that the 2 replaced entries are in fact duplicates. I'll look into the conversion script sometime tonight.

**Comment by DandelionSprout** [comment]
I acknowledge that there have been instances where companies somehow lost track of their subdomains, resulting in things like, as a hypothetical example, `gh7u83th5378t5378t5.stockholmflowershop.spider`. However, I cannot readily imagine that the Discord devs would ever fall victim to that for at least the next decade.

Nevertheless, as a result of https://github.com/AdguardTeam/HostlistsRegistry/blob/c5785759df226aca5e21323ee6f2f9b3d116024f/services/discord.yml#L10, I'll attempt to modify the entries a bit.

**Pull request closed without merging**
