### PR TITLE
Update LegitimateURLShortener.txt

### PR DESCRIPTION
**Pull request by shenzhiming88**
Rearranged the redundant parameters of this page

### CODE REVIEW

**Comment by iam-py-test** [comment]
I’m not sure about playurl, but the rest look ok.

**Comment by shenzhiming88** [comment]
> I’m not sure about playurl, but the rest look ok.

Well, could you please tell me what is the playurl? I'm sorry that I'm not good at English

**Comment by iam-py-test** [comment]
> > I’m not sure about playurl, but the rest look ok.
> 
> Well, could you please tell me what is the playurl? I'm sorry that I'm not good at English. I have used them for the long term, and no problem appeared.

It’s not your fault; I should have clarified what I meant.
I meant `||bilibili.com$removeparam=/^playurl/ `, but if you have used these for a while with no problems, then it must be ok

**Comment by shenzhiming88** [comment]
> I’m not sure about playurl, but the rest look ok.

These are no problem, including the play page, because I tested for a very long time.

**Comment by DandelionSprout** [comment]
I need to create a new PR guideline about requiring `^` after whole domains. 😅 

Other than that it looks good.

**Comment by shenzhiming88** [comment]
@DandelionSprout Fine. So can you help me add it? Thanks!

**Comment by DandelionSprout** [comment]
Indeed I can and have. 🙂

**Pull request merged**
