### PR TITLE
Update China IP

### PR DESCRIPTION
**Pull request by HankAviator**

### CODE REVIEW

**Comment by DandelionSprout** [comment]
IPv4 entries ending in `/32` should have that suffix removed to simply turn them into normal IP addresses.

So I'll fix that before merging.

**Comment by HankAviator** [comment]
I guess it was because of some consistency in notation?

**Comment by DandelionSprout** [comment]
Mostly help ensure at least *partial* compatibility with any tools that can handle IP addresses but not CIDRs; and also to save a few bytes of filesize.

**Comment by HankAviator** [comment]
There are only 6 /32 prefix addresses but ok 😄

**Pull request merged**
