### PR TITLE
Update LegitimateURLShortener.txt

### PR DESCRIPTION
**Pull request by shenzhiming88**
`https://mp.weixin.qq.com/s/E32x6-jUXUr1E4fZRfaFYA`
Will break the display of the QR code here
image

### CODE REVIEW

**Comment by iam-py-test** [comment]
Not 100% sure if this shouldn't go in the Allowlist section, but I guess it doesn't matter

**Comment by shenzhiming88** [comment]
@iam-py-test Oh, I seem to have only changed the date and not the version number.
Also, does `Dandelion Sprout's Anti-Malware List` handle content farms?

**Comment by iam-py-test** [comment]
> @iam-py-test Oh, I seem to have only changed the date and not the version number.

That's fine. It probably was corrected in https://github.com/DandelionSprout/adfilt/commit/957211e61fcfa7ae1f3f16c9b4dbd5004f00c6ff anyway
>  Also, does Dandelion Sprout's Anti-Malware List handle content farms?

That's a @DandelionSprout question - I can only give my opinion? Can you clarify what you mean? Do you have specific url(s)?

**Comment by iam-py-test** [comment]
Hmm...
Based on https://en.wikipedia.org/wiki/Content_farm, I'd say no, but they might deserve their own list

**Comment by shenzhiming88** [comment]
> Can you clarify what you mean?

https://en.wikipedia.org/wiki/Content_farm

These types of sites have no value and waste people's time. They use crawlers and plagiarize articles from other sites. And for Chinese, they may use translation tools to translate Chinese to English first and then translate English to Chinese so that users can't find the source.

**Comment by iam-py-test** [comment]
Again, that's an @DandelionSprout question.
I have tried to [block spam in my own list](https://github.com/iam-py-test/my_filters_001/blob/main/special_lists/anti-malware-ubo-extension.txt#L209), but I'm still not entirely sure that is somewhere Imre wants to go (In my opinion, it's a dark path)
Unethical, yes. If their selling it for money, then it's a scam and yes. 
I really have no idea 🤷

**Comment by DandelionSprout** [comment]
I've seen similar sites try to translate from German/Spanish/Hungarian/Polish to English by bot, but they'd have to be in a separate and currently not-existing list, which is at least several weeks away from being made due to needing immense research.

**Comment by shenzhiming88** [comment]
> I've seen similar sites try to translate from German/Spanish/Hungarian/Polish to English by bot, but they'd have to be in a separate and currently not-existing list, which is at least several weeks away from being made due to needing immense research.

For mainland China, you can refer to this.
https://github.com/cobaltdisco/Google-Chinese-Results-Blocklist/blob/master/GHHbD_perma_ban_list.txt

**Comment by shenzhiming88** [comment]
And, I think it would be better to hide these pages directly from the search results (e.g. Google and Bing). Thanks!

**Pull request merged**
