### PR TITLE
Merge app ads blocklist China into StayOnThePhoneBrowswer

### PR DESCRIPTION
**Pull request by HankAviator**

### CODE REVIEW

**Comment by DandelionSprout** [comment]
Seems good enough to me. Thanks! 💜

**Comment by HankAviator** [comment]
The list contains some self-promotion such as WeChat channel subscription QR code rules. They don't strictly match your description so you may wanna update that too?
Um should I also update version if necessary next time?

**Comment by DandelionSprout** [comment]
That would indeed be pretty far out of the list's scope, so I guess I'll remove the one such entry I could find.

Updating the version is very appreciated, though not mandatory.

**Comment by HankAviator** [comment]
I didn't see that you have any self-promo lists, otherwise it'll be nice to move the entries there.

**Comment by DandelionSprout** [comment]
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AdRemovalListForUnusualAds.txt can used for big-size promos for paid services, other than that I can mostly only recommend submitting them to AdGuard Annoyances Filter.

**Comment by HankAviator** [comment]
Ok I'll do PR to your list only when the QR codes get irritating enough. Thanks and goodnight 🌚

**Pull request merged**
