### PR TITLE
Address uBlockOrigin/uBlock-issues#2483

### PR DESCRIPTION
**Pull request by MasterKia**
uBO is rejecting `:before` filters and `::before` should be used instead (I noticed it in the dev build).

https://github.com/uBlockOrigin/uBlock-issues/issues/2483

I'm not aware whether you use `:before` in your other lists or not.

### CODE REVIEW

**Comment by krystian3w** [comment]
`:before` is older than `::before` and none of browsers disabled use.

**Review by krystian3w — COMMENTED** [review]
missed:

- https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianList.txt#L77

- https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianList.txt#L1205

- https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianList.txt#L1443

and maybe more:

> https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L8 https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L10 https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L11 https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L12 https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L13 https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L23 https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L24 https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L28 https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L29 https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L32 https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L38 https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L52 https://github.com/DandelionSprout/adfilt/blob/9b082916a2e0a12b16a0aa7e9c163e3e55f1522c/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L54

Maybe header need bump date and version.

**Comment by DandelionSprout** [comment]
For even better effect, I can simply do a Ctrl+Shift+F of the entire Adfilt repo in Sublime Text, which should pretty much eliminate the chance of missing any cases of these syntaxes.

**Comment by krystian3w** [comment]
Hold on, with too simple changer you generate somewhere:

`:::before`
`:::after`

due few files have CSS3 syntax.

**Comment by DandelionSprout** [comment]
I'm splendid with RegEx, and can easily limit the replacement to stuff like `([a-zA-Z0-9#]):(before|after)` → `\1::\2`

**Comment by krystian3w** [comment]
`https://github.com/uBlockOrigin/uAssets/issues/16666#issuecomment-1424097227`

**Comment by krystian3w** [comment]
Human readable file is a little outdated:

https://github.com/DandelionSprout/adfilt/blob/master/Wiki/SyntaxMeaningsThatAreActuallyHumanReadable.md

> `:before` / `:after`: Removes the pseudo-elements that belong to a page element. If a pseudo-element is present, they're shown as standalone `::before` or `::after` lines in all-brown in the F12 filetree.

Ways:

- add colons
- add info about dropping by uBo 1.46.2+

**Comment by DandelionSprout** [comment]
I guess I can handle the colon stuff, at least.

**Pull request closed without merging**
