### PR TITLE
Update LegitimateURLShortener.txt

### PR DESCRIPTION
**Pull request by Nojuuu**
Removes `ref`:
* `https://www.woot.com/plus/save-on-solid-state-drives?ref=w_gw_dd_3`
* `https://www.goodreads.com/blog/show/2199-cuddle-up-with-these-new-holiday-romances-and-cozy-mysteries?ref=book-show`
* `https://www.comixology.com/Avengers-Forever-2021-1/digital-comic/967652?ref=c2l0ZS9hamF4U2xpZGVyL2Rlc2t0b3Avc2xpZGVyTGlzdC8zNDc3OQ`
* `https://www.bookdepository.com/1984-George-Orwell/9780141036144?ref=pd_gw_1_pd_gateway_1_1`
_______

Removes `^pf_rd_`:
* `https://www.6pm.com/men/agEEwAEC4gICGA0.zso?s=isNew%2Fdesc%2FgoLiveDate%2Fdesc%2FrecentSalesStyle%2Fdesc%2F&pf_rd_p=80a84fb7-2432-4609-b5fe-c667243ddb8f&pf_rd_r=ED858D21FC5946CDA69A`
* `https://www.audible.co.uk/pd/Ramble-Book-Audiobook/0008293368?plink=jNCwFiYvWi3iSh2g&pf_rd_p=ab7f9b8c-a03d-488b-a24b-c34000fee893&pf_rd_r=7HVH9AZS88GVGWRP0DMV`

_______

Removes `pid`:
* `https://www.farfetch.com/shopping/men/wales-bonner-stripe-embroidered-sports-jacket-item-16667500.aspx?fsb=1&size=21&storeid=13541&pid=google_search&shopping=yes`

______

Removes `plink`:
* `https://www.audible.co.uk/pd/Ramble-Book-Audiobook/0008293368?plink=jNCwFiYvWi3iSh2g&pf_rd_p=ab7f9b8c-a03d-488b-a24b-c34000fee893&pf_rd_r=7HVH9AZS88GVGWRP0DMV`

### CODE REVIEW

**Comment by Nojuuu** [comment]
Maybe could also remove the `plink` from that audible url as it is probably Amazon tracking too?

**Comment by iam-py-test** [comment]
Once you'v done that, I can merge

**Comment by Nojuuu** [comment]
Done.

**Comment by iam-py-test** [comment]
Thanks @Nojuuu

**Pull request merged**
