### PR TITLE
Whitelisted shorter.cf in Dandelion Sprout's Anti-Malware List.txt

### PR DESCRIPTION
**Pull request by BLACK4585**

### CODE REVIEW

**Comment by DandelionSprout** [comment]
Doesn't seem to me that their main page is loading correctly. 
image

Do you have any example links that do load correctly?

**Comment by iam-py-test** [comment]
Loads fine for me.

**Comment by DandelionSprout** [comment]
Checking deeper now with this setup, the service's GitHub link (on the bottom in the screenshot) seems to be dead, which is probably not a good sign. 
image

However, as there seems to be 0 indications that the site is used in spam SMS or E-mails and such, I agree to the whitelisting.

**Comment by BLACK4585** [comment]
We just made the Repo of the Shorter private this morning since it didn't have any use cases anymore xD. 
But now everything is up and working again, you can check out the GitHub via the provided link.
Thank you for whitelisting!

**Pull request merged**
