### PR TITLE
Update China IPs

### PR DESCRIPTION
**Pull request by HankAviator**
Upstream: https://raw.githubusercontent.com/pexcn/daily/gh-pages/chnroute/chnroute.txt
Note [the upstream repo](https://github.com/pexcn/daily) is distributed under GPL-3.0. Review of license compatibility with Dandelicence is advised.

### CODE REVIEW

**Comment by HankAviator** [comment]
Please validate removed entries.

**Comment by DandelionSprout** [comment]
My licence was handcrafted to take care of things like these, which I've now done by adding creditation, and by using a provision in my licence where paragraphs can be given licences of their own (in this case GPL-3.0).

**Comment by HankAviator** [comment]
Do you reckon submodules are useful in maintenance?

**Comment by DandelionSprout** [comment]
Dealing with actual git submodules, is far beyond my coding skills. But it looks to me like it'd be pretty convenient for those who know how to create them.

**Comment by HankAviator** [comment]
Consider it done! (I think I'm worse than you but I'd like to try)

**Pull request merged**
