### PR TITLE
Update LegitimateURLShortener.txt

### PR DESCRIPTION
**Pull request by DeepChirp**
Updates as https://github.com/DandelionSprout/adfilt/pull/304#issuecomment-945031069 suggests

### CODE REVIEW

**Comment by iam-py-test** [comment]
Thanks for making these changes

**Comment by shenzhiming88** [comment]
But the structure of the rules may still be a bit messy, and perhaps we need more time to organize them (e.g., divide the rules into general and specific)

**Comment by iam-py-test** [comment]
I never though of that. It is late here (where I live anyway) so I will have to continue in the morning

**Comment by shenzhiming88** [comment]
> I never though of that. It is late here (where I live anyway) so I will have to continue in the morning

Fine. After all, it may be a hard work. And thank you for your help!

**Pull request merged**
