### PR TITLE
Block Kode24 preview sections

### PR DESCRIPTION
**Pull request by fredrik-lindseth**
# Block Kode24 preview sections

### CODE REVIEW

**Comment by iam-py-test** [comment]
@fredrik-lindseth I'm sorry, but I do not understand.
These don't look like ads to me - I did have to translate it, but it seemed they are more like articles:
image

Also, the filter .preview seems to make some pages completely blank:
image

**Comment by DandelionSprout** [comment]
I'm siding with iam-py-test on this. The suggested entry would be disastrous.

I can only presume Fredrik wanted to block `###company-sponsors-list` instead, which I'd have to think more about.

**Comment by fredrik-lindseth** [comment]
The .preview blocks some ads, side banners, and some "do you want to read about this instead" in the middle of articles. I could always suggest adding it to Annoyances instead.
I did not see any pages that broke completely. Do you have an URL?

**Comment by DandelionSprout** [comment]
The total breakage occurs on the frontpage (`https://www.kode24.no/`), from what I can determine.

**Comment by iam-py-test** [comment]
Also on `https://www.kode24.no/emne/l%C3%B8nn` I think

**Review by krystian3w — CHANGES_REQUESTED** [review]
too wide

**Comment by iam-py-test** [comment]
@DandelionSprout should this be closed?

**Comment by krystian3w** [comment]
Author uncheked edit PR for Collaborators?

**Comment by iam-py-test** [comment]
> 
> 
> Author uncheked edit PR for Collaborators?

No

**Comment by DandelionSprout** [comment]
I am in favour of closing after fredrik-lindseth failed to write anything that'd further his case, which I'll do now.

**Pull request closed without merging**
