### PR TITLE
Remove some hard coded values

### PR DESCRIPTION
**Pull request by johand199**
VG decided to have more than just 6 ad's on the page, so this will take care of that

### CODE REVIEW

**Comment by DandelionSprout** [comment]
Those entries were actually chiefly designed with Adressa in mind, so I'll test out some stuff there for a few minutes. I'll get back to you right afterwards.

**Comment by DandelionSprout** [comment]
I struggle to detect `vg.no##div[id^="ad-front-netboard_"]` in Nano Adblocker's logging function, or any of the netboard entries either. Nevertheless I see nothing wrong with adding `vg.no##div[id^="ad-front-netboard_"]` to the list, which I'll do within 30min.

**Comment by johand199** [comment]
Aha. i tried to look for other websites using it, but never checked Adressa

**Comment by DandelionSprout** [comment]
I'll restore those entries manually (since I currently appear to have editing rights for this pull request), and will then merge it and thank you for the help. 🙂

**Pull request merged**
