### PR TITLE
Syntax update AntiMalwareTPL.tpl

### PR DESCRIPTION
**Pull request by lordhugo7880**
Corrections/additions for TPL syntax

### CODE REVIEW

**Comment by DandelionSprout** [comment]
I've attempted to change it to `-d www.majorgeeks.com images icons red_icon_18x17px.png` now, as that's how I've always thought that the TPL syntax was supposed to be like. But I'll test that entry and site a bit better within the next hour.

**Comment by DandelionSprout** [comment]
Okay, so after trying out such approaches as `-d www.majorgeeks.com images icons red_icon_18x17px.png`, `-d majorgeeks.com red_icon_18x17px.png`, and `- red_icon_18x17px.png`, I came to the conclusion that TPL's syntax remains complete witchcraft to me, and that [Microsoft's official TPL syntax guide](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/hh273399(v=vs.85)) is both lackluster and occasionally flat-out lying.

Even more so after I tested out ways to fix similar entries from [the TPL version of my Nordic list](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/DandelionSproutsNorskeFiltre.tpl) (such as `-d amino.dk images partners agera 240x140-forside-hardcoded*.jpg` and `-d eyjar.net skrar ads`, the latter of which I even tried to use `-d eyjar.net /skrar/ads` on) and consistently failed at it.

All in all, Microsoft made an extremely bad job back when they created the TPL system, especially when they gave it *no logging tools whatsoever*, and this has become a huge setback against my attempts at being one of the last two active TPL list makers in existence (alongside the EasyList team).

**Comment by lordhugo7880** [comment]
I agree that the documentation by Microsoft is insufficient. I wasn't actually aware of the specific syntax guide you sent, so thank you for that. I did know of these pages: [msAddTrackingProtectionList method](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/gg593069(v%3Dvs.85)) and [Web Tracking Protection](https://www.w3.org/Submission/web-tracking-protection/)
The first link is similar to the one you sent, but the content is more summarized, and the second link contains the proposal Microsoft made in 2011 to make IE TPL a web standard. With the exception of `FilterList` instead of `msFilterList` it contains the same syntax.
Based on the documentation, `-d amino.dk images partners agera 240x140-forside-hardcoded*.jpg` should be inaccurate because of `Domain rules can also specify an optional substring to match. There can be only **one** substring per domain rule line.` [emphasis mine] .
`-d eyjar.net /skrar/ads` should also be inaccurate because of `The following block domain rules will not match:

    -d orderform.contoso.com
    -d contoso.com /path/file.html
` I.e. it seems the string at the end of a domain block rule is not allowed to begin with `/` .

**Comment by DandelionSprout** [comment]
Thanks for the links; I've posted them on https://hub.filterlists.com/t/resources-for-writing-filters/12/6 now and will look more deeply into them at some point in the near future.

**Pull request closed without merging**
