### PR TITLE
Add filters for Version2.dk inline ads

### PR DESCRIPTION
**Pull request by runejuhl**
This PR adds filters for inline ads on version2.dk

Before:

image

After:

image

### CODE REVIEW

**Comment by DandelionSprout** [comment]
From what I could determine, I can't *readily* block the "Skræddersy ditt erhvervsabonnement" box, since it's about subscriptions to that same site. Major regional adblock lists kinda have to strict on such, though [AdGuard Annoyances Filter](https://github.com/AdguardTeam/AdguardFilters/issues) would probably be interested in blocking it.

As there's *two* job sliders on articles, I agree to blocking the first one.

Often there's an ad banner on top, at least on PC, that can most certainly be blocked. Give me 7min.

**Comment by runejuhl** [comment]
Let me know if there's anything you want me to change, I'd be happy to help. Just got bothered enough by the ad overload on that site that I had to do something :sweat_smile:

**Comment by DandelionSprout** [comment]
I've come up with 3 entries that I'm confident will solve a large part of the overload:
```
version2.dk,ing.dk,techmanagement.dk,radar.dk##div[class^=layout] > .block-tm-kevel
version2.dk,ing.dk,techmanagement.dk,radar.dk##div:not([class]) > .jobs-wrapper
||service.tekhus.dk/*.jpg^$image,third-party
```
These will be added to the uBlock Origin list version within 5min, and to the AdGuard and ABP versions later today. 🌞

**Comment by runejuhl** [comment]
Awesome, thanks a lot @DandelionSprout!

**Pull request closed without merging**
