### PR TITLE
Create a file about all the lists here

### PR DESCRIPTION
**Pull request by iam-py-test**
This PR adds a directory for the lists in this repo
It is far from being done but I figured I would open this PR just to share the concept

### CODE REVIEW

**Comment by DandelionSprout** [comment]
I remember trying to add and frequently update such a directory back in 2018: https://github.com/DandelionSprout/adfilt/blob/e5d588c843a2f511789863db4acf1b1fb6886d90/.github/README.md. It took up **a lot** of time and effort, even with less than 25 lists.

Making such a directory that could potentially span ≥130 list is not a good idea. Take my word for that.

**Comment by iam-py-test** [comment]
> I remember trying to add and frequently update such a directory back in 2018: https://github.com/DandelionSprout/adfilt/blob/e5d588c843a2f511789863db4acf1b1fb6886d90/.github/README.md. It took up **a lot** of time and effort, even with less than 25 lists.
> 
> Making such a directory that could potentially span ≥130 list is not a good idea. Take my word for that.

Then maybe just one for your main/popular lists?
Note: I have seen implementations, though with fewer lists - https://github.com/blocklistproject/Lists#main-lists

**Comment by DandelionSprout** [comment]
>Then maybe just one for your main/popular lists?

I'd need to think for a while about that, at least. I'm currently recovering from a 4-day fever I had this weekend as well.

**Comment by iam-py-test** [comment]
> > Then maybe just one for your main/popular lists?
> 
> I'd need to think for a while about that, at least. I'm currently recovering from a 4-day fever I had this weekend as well.

Oh, sorry. Hope you feel better.

**Comment by DandelionSprout** [comment]
One thing that makes this further complicated, is: Which versions of Nordic Filters would need to be included in a table like this? The uBO, AdGuard, ABP-Inclusion, Hosts, and raw domain versions all have valid cases for being important enough for inclusion, or not.

**Comment by Nojuuu** [comment]
image

What if you do something like that, but clicking on the logo would take you to a list optimised for that software?

**Comment by iam-py-test** [comment]
> image
> 
> What if you do something like that, but clicking on the logo would take you to a list optimised for that software?

Might need some explanation though...
Some people might get confused and add the wrong version for the wrong software

**Comment by DandelionSprout** [comment]
I don't think such a function is realistically possible to do on GitHub, unfortunately.

**Comment by iam-py-test** [comment]
> I don't think such a function is realistically possible to do on GitHub, unfortunately. It'd require _way_ too much work.

Just linked images:
<a href="https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt"></a>

**Comment by DandelionSprout** [comment]
Okay, so, after setting off 20min today (some weeks late) to think about this, I sadly can't imagine a way to format that list that would've made it a preferable alternative to using FilterLists.com.

For instance, the list doesn't have any clearcut way of preventing users of Pi-hole or ABP from trying to use Annoyances List and then get angry at me when it doesn't work for them. And as much passion and love I put into the anti-FiM and anti-futa lists, the 14 filterlists displayed in this PR at the time of writing omit many other lists that are considered even more well-suited for broad use (*Dandelion Sprout's Website Stretcher* comes to mind, but is not the only one).

So I'm going to take a bit of a gamble here, by closing the PR for the time being and hope it doesn't cause any bad feelings.

**Comment by iam-py-test** [comment]
> Okay, so, after setting off 20min today (some weeks late) to think about this, I sadly can't imagine a way to format that list that would've made it a preferable alternative to using FilterLists.com.

I guess this wasn't really viable, especially considering Markdown is more limited than a whole website
> For instance, the list doesn't have any clearcut way of preventing users of Pi-hole or ABP from trying to use Annoyances List 

Does Filterlists.com do that? 
> And as much passion and love I put into the anti-FiM and anti-futa lists, the 14 filterlists displayed in this PR at the time of writing omit many other lists that are considered even more well-suited for broad use (Dandelion Sprout's Website Stretcher comes to mind, but is not the only one).

As this was just an idea, I just collected a few of your lists that I knew enough about. If it was actually going to be implemented, those lists would be added. I'm sorry if I offended you
> So I'm going to take a bit of a gamble here, by closing the PR for the time being and hope it doesn't cause any bad feelings.

If you are talking about me (which is what I assume and not the other people who commented on this PR), I understand your reasoning. (I actually tried this on my lists, and I agree that it is hard to maintain - https://github.com/iam-py-test/my_filters_001/commit/0ea64d7cf8565c56faa2751d65761adfe5a4d659)

**Comment by DandelionSprout** [comment]
>Does Filterlists.com do that?

Kind-of. By going to its "Software" bar and picking Pi-Hole, only the lists that support Pi-Hole show up.

>As this was just an idea, I just collected a few of your lists that I knew enough about. If it was actually going to be implemented, those lists would be added. I'm sorry if I offended you
>
>If you are talking about me (which is what I assume and not the other people who commented on this PR), (...)

It was just that this was going a *very* difficult PR to bring to a good state (since potentially as many as 70 filterlists would've been needed, which'd take me some 3 hours), but at the same I knew you had put effort and time into it, and that it was a somewhat requested feature. So I feared people would react to my closure with *"Oh, come on, Dandee, people could've needed this"*. 😅

**Pull request closed without merging**
