### PR TITLE
Update LegitimateURLShortener.txt

### PR DESCRIPTION
**Pull request by shenzhiming88**
Update for `Bilibili`

### CODE REVIEW

**Comment by shenzhiming88** [comment]
@iam-py-test It seems that this parameter cannot be removed, and it will be reloaded again
See https://github.com/the1812/Bilibili-Evolved/discussions/3424#discussioncomment-2918252, here is a script to remove
```js
exports.vdSourceClean = {
  name: 'vdSourceClean',
  displayName: '网址参数清理 - vd_source',
  setup: ({ addData }) => {
    addData('urlParamsClean.params', params => params.push('vd_source'))
  },
}
```
I don't know if uBO can remove it. Can you have a try?

**Comment by iam-py-test** [comment]
Are you aware of any example URLs? I didn't see any on that report

**Comment by shenzhiming88** [comment]
> Are you aware of any example URLs? I didn't see any on that report

You have to register and log in to an account, and then open a random video, this parameter will always appear and cannot be removed.

**Comment by iam-py-test** [comment]
Ok. I have _way_ too much to do this week, so it may take a while before I can get a test account.

**Pull request merged**
