### PR TITLE
Update uBlockOrigin/uAssets#1495

### PR DESCRIPTION
**Pull request by smed79**
https://forums.lanik.us/viewtopic.php?f=62&t=39468

### CODE REVIEW

**Comment by smed79** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=39468

**Comment by DandelionSprout** [comment]
Hmm, I see.

Is there by the way any specific reason for why your entry suggestion blocks Elderlyscissors as a whole, instead of just on ITavisen?

**Comment by smed79** [comment]
I do not know of any useful or legitimate use for admiral domains these which are used only for tracking and blocking adblock users.

**Comment by DandelionSprout** [comment]
Sounds like a good enough reason for me to add that filter. Especially the part about it blocking adblock users.

But shouldn't this most ideally have been a part of e.g. Nano Defender Integration, which has a wider userbase (both in numbers and geography) than my Norwegian list... or?

**Comment by DandelionSprout** [comment]
In the meantime I suppose that I'll stop beating around the bush and will accept the pull request for now.

**Comment by DandelionSprout** [comment]
As for the domains.list-list, it could easily be converted to uBlock Origin format for the world to enjoy, probably even as a combined domains and uBO format at once, just by adding some `# Title:` and `# Expires:` among the first few lines, which most likely wouldn't have interfered with its function as a domains list.

**Pull request merged**
