### PR TITLE
Update LegitimateURLShortener.txt

### PR DESCRIPTION
**Pull request by git-101-collab**
Removed more parameters from affiliate networks.

Removing `pdBoUid` caused problems loading pages with that parameter (`https://www.jdwilliams.co.uk/shop/switch-neon-inc-rayman-and-spongebob/bm593/product/details/show.action?pdBoUid=3156`) btw

### CODE REVIEW

**Comment by git-101-collab** [comment]
More links:

```
! https://www.wiggle.co.uk/scicon-phone-handlebar-bag?kk=a4c6361-17cd849c3bd-1058a6
! https://www.hellyhansen.com/en_gb/external-life-pocket-67430?kk=a4c6368-17cd8483bbe-10595a&color=301324
! https://infantdeco.es/producto/pizarra-de-madera-portatil-con-smartphone/?kk=a4c6365-17cd7f25480-1014b8&from=kelkooes
! https://www.worten.es/productos/informatica/software/antivirus/software-norton-360-standard-10-gb-1-dispositivo-1-ano-smartphone-pc-y-tablet-formato-digital-7321680?kk=a4c6368-17cd7f25b6b-101208&from=kelkooes
! https://www.avpartsmaster.co.uk/konftel-300-teleconferencing-phone-p160578/s160541?kk=a4c6361-17cd849c62d-1058a8
! https://www.secretsales.com/60d3442d37bba-michael-kors-michael-kors-michael-kors-rose-small-north-south-phone-crossbody-black/?kk=a4c6368-17cd84b3c9e-105c22
! https://www.popinabox.co.uk/clothing/scooby-doo-hold-the-phone-kids-t-shirt-white/12051046.html?kk=a4c6365-17cd84b43f2-105ed3&affil=thgppc
! https://www.mankind.co.uk/nails-inc.-what-the-shell-call-me-on-my-shell-phone-top-coat-14ml/12545243.html?kk=a4c6361-17cd8516d36-105efb
! https://www.geekgearbox.com/product/cbgb-home-of-rock-phone-cover/?kk=a4c6368-17cd85271f5-106dc
! https://www.godsejeren.dk/products/phone-case-3-card-iphone-12-12pro-sort?pa-partnerid=22947&pacid=617fcb66eb3c23.08348327
! https://shopping.coop.dk/vare/gurli-gris-interaktiv-legetoejsmobil-flip-og-learn-phone-laer-om-tal%2C-bogstaver-og-farver-med-gurli-og-hendes-venner/5060062144734?paid=22947&pacid=617fcc96d405e1.64163442&cid=affiliate5738561478
! https://www.glasses.com/gl-us/collection-glasses?cid=PM-ACJ_000000-1397064_Offers.com+-+Vertive%2C+LLC_14046264
! https://www.plusbog.dk/phone-for-the-fish-knives-daisy-waugh-9780349422480?affiliate=8928
! https://www.viking-direct.co.uk/en/targus-35.8-cm-14.1-laptop-privacy-screen-for-laptop-169-p-6124590?clickref=1101liwQHqn7&src=ph
! https://www.lindy.co.uk/usb-c4/usb-3-2-gen-2-type-c-mini-docking-station-hdmi-pd-3-0-100w-usb-3-2-gen-2-gigabit-p13380/s13540?clickref=1100liwZeMIu
! https://www.wayfair.co.uk/Symple-Stuff--HeightAdjustable-Phone-Swivel-Arm-with-Supporting-Plate-E111303508-L6439-K~STYO1242.html?refid=KDUK321-STYO1242
! https://www.gucci.com/uk/en_gb/pr/men/accessories-for-men/tech-accessories-for-men/iphone-cases-for-men/ophidia-phone-case-fits-iphone-12-pro-max-p-668408K5I0S9742?siteID=Sl5uPV1NkiY-l0_MTexqwJtrMdfzhKaWhw&PublisherSID=3642857&PubName=Kelkoo+UK
! https://www.batteryupgrade.co.uk/shopBrowser.php?assortmentProductId=81029723&shopGroupId=12849102&tracker=kelkoo_uk&currencyId=30000000&langId=1
! https://www.johnstonprams.com/en/gb/Jane-Pram-Handlebar-Organiser-Bag---Black/s-3672-9634.aspx?PartnerID=53
! https://www.sportler.com/it/p/fjaellraeven-kanken-laptop-13-zaino-tempo-libero-10788950?campaign=feed%2Fde%2F11189%2Fkelkooit%2F2154760-2&partnerid=kelkooit
! https://focusmart.it/prodotto/fotocamera-compatta-canon-powershot-sx740-hs-black/?from=kelkooit
! https://www.dell.com/fr-fr?publisherid=1607869&publisher
! https://www.retrospect.com/en?AFFSRC=s1_0_8593971
! https://blog.linkconnector.com/technology/lc-atid/
! https://disq.us/url?url=https%3A%2F%2Farstechnica.co.uk%2Finformation-technology%2F2017%2F01%2Fantivirus-is-bad%2F%3Av0Er-2ea1-t4FcbndbRV_9xv5-4&cuid=977864
! https://knowledge.sovrn.com/how-to-track-specific-users-or-links-with-cuid
! https://www.idevlibrary.com/docs/Custom_Links.pdf
! https://adtraction.com/blog/what-is-epi-and-how-does-it-work
! https://www.bhphotovideo.com/c/product/1568272-REG/crucial_ct2000p5ssd8_2tb_p5_nvme_pcie.html/BI/20811/KBID/16572?SID=tomshardware-us-1262443439976563500
! https://www.postaffiliatepro.com/integration-methods/affilimate/
! https://proprivacy.com/goto/10minutemail/disposableemail_p.2.bestbuytable.cta_t.2_l.en_pid.9441
! https://support.avantlink.com/hc/en-us/articles/360061140991-Anatomy-of-an-Affiliate-Tracking-Link
! https://www.tiktok.com/?c=homepage_hot&af_adset=organic&pid=tiktokwebseo&af_siteid=pc&af_ad=send_download_link&af_ad_id=bing
! https://play.google.com/store/apps/details?id=net.bitburst.pollpay&c=Poll%20Pay%20Web%20Landing%20Page
! https://www.calm.com/?pid=googlesem&af_channel=googlesem&af_c_id=14967949669&af_adset_id=131478100227&af_ad_id=553575011255&af_sub_siteid=&af_keyword=calm&af_sub3=e&af_sub4=Cj0KCQjwtrSLBhCLARIsACh6Rmi02etwYlXcQzgM76WCRA8Hm4nqTD-7SGPZaEVlAkX2sOVI_r6IedAaAiTbEALw_wcB&af_sub5=xx
! https://gojek.onelink.me/2351932542?af_force_deeplink=true&pid=Go-Jek_Web&c=MART_Sem_Traffic_Page&af_channel=Organic&af_adset=MART_Sem_Traffic_Page&af_ad=MART_Sem_Traffic_Page&is_retargeting=true&af_click_lookback=7d&af_dp=gojek://gobuy/home&af_web_dp=https://www.gojek.com/gomart/&utm_source=Go-Jek_Web&utm_medium=Referral&utm_campaign=MART_Sem_Traffic_Page&utm_term=MART_Sem_Traffic_Page&utm_content=MART_Sem_Traffic_Page
! https://oxygen.us/?c=OxygenUserinvites&af_referrer_uid=1633725426825-7863484&af_referrer_customer_id=1055947&pid=af_app_invites
! https://old.reddit.com/domain/onelink.me/
```

**Comment by iam-py-test** [comment]
Ok, let me look over this later today

**Review by shenzhiming88 — APPROVED** [review]
Awesome!

**Comment by iam-py-test** [comment]
@git-101-collab do you know any websites which use `s2` for tracking, because that rule seems like it might cause breakage (and did - https://github.com/DandelionSprout/adfilt/discussions/163#discussioncomment-1814141)

**Comment by git-101-collab** [comment]
@iam-py-test Actually no, just the test links [here](https://support.getcake.com/support/solutions/articles/13000081927-how-to-use-direct-linking-when-tracking-links-are-not-allowed), I shouldn't have included them, so sorry. It is best to remove them (`s1-5`).

**Comment by iam-py-test** [comment]
> @iam-py-test Actually no, just the test links [here](https://support.getcake.com/support/solutions/articles/13000081927-how-to-use-direct-linking-when-tracking-links-are-not-allowed), I shouldn't have included them, so sorry. It is best to remove them (`s1-5`).

It's always a tradeoff between privacy and breakage. I wasn't criticizing you, I was just asking
Fixed in https://github.com/DandelionSprout/adfilt/commit/b069e67a4cf99a0eecb573273c93de739728b8fb

**Pull request merged**
