### PR TITLE
Add some more insane preachers

### PR DESCRIPTION
**Pull request by deletescape**

### CODE REVIEW

**Comment by DandelionSprout** [comment]
I'm in need of the context behind these entries. They seem to me at first sight to be Hare Krishna with a hint of cult-of-personality, but are there anything about these 9 sites that stand out from other Hare Krishna sites/movements, or which meet any of the criteria in the list's top description section?

**Comment by deletescape** [comment]
Most of these hare Krishna sites are directly linked on swiss sects watchlists, but they are probably still debatable and I don't have too much background on them. I'll do some more research again tomorrow and add context/reduce the list again.

**Comment by DandelionSprout** [comment]
If you can find me links to those watchlist pages, that'd be great. But I won't pressure you tonight if you're short on time. 🙂

**Comment by deletescape** [comment]
Alright, I read up on the swiss ISKCON in a document from infoSekta (http://www.infosekta.ch/media/pdf/I_ISKCON_2009.pdf). And as it turns out they don't really follow sect characteristics anymore and actually help people leave their group if they want to do so. While this document is from 2009 I believe this has hardly changed much since then and we can probably remove them from this PR. I am even less sure about the current state of their international groups and will thus remove them as well.

**Comment by deletescape** [comment]
On the remaining two entries:
For info on KSB (Kwasizabantu ) see https://www.ksb-alert.com
GFC (Gemeinde für Christus) believes that they have to bring all people (especially from non christian countries) to their Believe or they will land in Hell (https://www.gfc.ch/ueber-uns/glaubensgrundlage/). They are debatable as well as they don't seem directly hostile (at least from what I have seen), but they do seem to be walking a thin line to being a sect. Maybe we should remove them as well?

**Comment by DandelionSprout** [comment]
While a Google search of `Kwasizabantu` didn't reveal any third-party accounts of insanity, it's pretty telling when `KSB-Alert` admits that non-believers have had horrendous experiences with it.

To my disappointment, I have not been able to find any third-party accounts that connect `GFC` to being a sect, and am left with having to gamble on them being Rapture-prophecising weirdos. Moreover I can't find the paragraph about going to Hell on the page you linked to.

I'll do some changes to this PR on my own, then I'll merge it.

**Pull request merged**
