### PR TITLE
Update StopAutoplayOnYouTube.txt

### PR DESCRIPTION
**Pull request by KnightmareVIIVIIXC**
how to automatically turn off autoplay on Dailymotion through one or more uBlock Origin entries
Or this for Adguard:
`dailymotion.com##+js(set, inlinePlayer.setAutoPlay, false)`
Or this for Adblock:
`dailymotion.com##script:inject(noeval.js, inlinePlayer.setAutoPlay, true)`
I forgot to add the Adguard/Adblock entries. My bad. :(

### CODE REVIEW

**Comment by iam-py-test** [comment]
> dailymotion.com * inlinePlayer.setAutoPlay false

I'm sorry, but that isn't a valid filter?

**Comment by KnightmareVIIVIIXC** [comment]
Are you talking about the autoplay on the homepage of daily motion or something else?

**Comment by iam-py-test** [comment]
Yes, I am talking about the autoplay on the homepage. Maybe I did something wrong with that scriptlet, but `dailymotion.com * inlinePlayer.setAutoPlay false` isn't a valid filter in uBlock Origin.

**Comment by KnightmareVIIVIIXC** [comment]
That script just turns of autoplay buttons I think. My bad again. I misunderstood. 0 for 2.

**Comment by iam-py-test** [comment]
I'll leave this up to Imre

**Comment by KnightmareVIIVIIXC** [comment]
Not sure if this is helpful or not, but when I use the element picker on the first video, this is what uBO is blocking:
`||www.dailymotion.com/embed?api=postMessage&apimode=json&app=com.dailymotion.neon&autoplay-mute=true&client_type=website&collections-action=trigger_event&collections-enable=fullscreen_only&endscreen-enable=false&info=false&like-action=trigger_event&like-enable=fullscreen_only&queue-enable=false&sharing-action=trigger_event&sharing-enable=fullscreen_only&ui-logo=false&watchlater-action=trigger_event&watchlater-enable=fullscreen_only&dmTs=281120&wait-for-custom-config=1`

**Comment by DandelionSprout** [comment]
`dailymotion.com * inlinePlayer.setAutoPlay false` seems like it was designed as a uMatrix entry, but I don't think that's how uMatrix works like. And "My Filters" in uBO is recognising it as a *comment* rather than an entry.
image

I've had severe stomach aches for a day now and lack much ability to test entries, but I suppose we'll need to see if some modified version of `dailymotion.com##+js(set, inlinePlayer.setAutoPlay, false)` would work or not.

**Comment by KnightmareVIIVIIXC** [comment]
Yeah I've heard about the ache de la stomache. I just don't get how that affects things. It may be a thing that can't be fixed due to how it's implanted into the site.

**Comment by DandelionSprout** [comment]
It means I've got limited resources and time to test it, since `dailymotion.com##+js(set, inlinePlayer.setAutoPlay, false)` doesn't immediately seem to work verbatim.

**Pull request closed without merging**
