### PR TITLE
Update LegitimateURLShortener.txt

### PR DESCRIPTION
**Pull request by Nojuuu**
Move to 
https://github.com/DandelionSprout/adfilt/blob/6efa3ddf52c07e1e0948856222d08cbe08bd60e0/LegitimateURLShortener.txt#L1873

### CODE REVIEW

**Comment by Nojuuu** [comment]
Should these be in `!!! ——— Google Search ———` section?

https://github.com/DandelionSprout/adfilt/blob/6efa3ddf52c07e1e0948856222d08cbe08bd60e0/LegitimateURLShortener.txt#L645-L649

https://github.com/DandelionSprout/adfilt/blob/6efa3ddf52c07e1e0948856222d08cbe08bd60e0/LegitimateURLShortener.txt#L2384-L2386

https://github.com/DandelionSprout/adfilt/blob/6efa3ddf52c07e1e0948856222d08cbe08bd60e0/LegitimateURLShortener.txt#L3325-L3326

https://github.com/DandelionSprout/adfilt/blob/6efa3ddf52c07e1e0948856222d08cbe08bd60e0/LegitimateURLShortener.txt#L3876-L3877

**Comment by iam-py-test** [comment]
> Should these be in !!! ——— Google Search ——— section?

I will probably rename this to Google and move those entries. Merging this in the meantime.
Thank you for your contributions.

**Comment by iam-py-test** [comment]
> Should these be in `!!! ——— Google Search ———` section?
> 
> https://github.com/DandelionSprout/adfilt/blob/6efa3ddf52c07e1e0948856222d08cbe08bd60e0/LegitimateURLShortener.txt#L2384-L2386

https://github.com/DandelionSprout/adfilt/discussions/163#discussioncomment-5727326. Not going to move them yet.
> 
> https://github.com/DandelionSprout/adfilt/blob/6efa3ddf52c07e1e0948856222d08cbe08bd60e0/LegitimateURLShortener.txt#L3325-L3326
> 
> https://github.com/DandelionSprout/adfilt/blob/6efa3ddf52c07e1e0948856222d08cbe08bd60e0/LegitimateURLShortener.txt#L3876-L3877

Moved in https://github.com/DandelionSprout/adfilt/commit/89ddd0d1194aa13af3c4bf5d078e07566eb0973c.

There are a few other YouTube entries, not sure what to do with them.

**Comment by Nojuuu** [comment]
I only found this Google Translate related:

https://github.com/DandelionSprout/adfilt/blob/89ddd0d1194aa13af3c4bf5d078e07566eb0973c/LegitimateURLShortener.txt#L1348-L1349


there's also a typo, it should be `_x_tr_pto`

**Comment by iam-py-test** [comment]
Thanks. Moved and fixed in https://github.com/DandelionSprout/adfilt/commit/afdbb534b3ff025b46131bba17f77f8cc05a99c0

**Pull request merged**
