### PR TITLE
Allow TLD: core.pw

### PR DESCRIPTION
**Pull request by yokoffing**
Needed for Wargaming Games

https://myip.ms/view/hosts/2920936/core_pw.html

### CODE REVIEW

**Comment by iam-py-test** [comment]
I can't seem to be able to connect to port 80 or 443: https://sitecheck.sucuri.net/results/https/core.pw
I don't see any DNS from my sandbox either when going to `https://wargaming.net` and downloading a random game, or any reference in the HTML source code of said domain.

**Comment by yokoffing** [comment]
> I can't seem to be able to connect to port 80 or 443: https://sitecheck.sucuri.net/results/https/core.pw

I couldn't get it to connect either.

pinging @hagezi for clarification

**Comment by hagezi** [comment]
In the game of e.g. World of Tanks or World of Warships, calls are made to *. core.pw.
I had blocked pw and the family complained that the wargaming games no longer worked.

**Comment by iam-py-test** [comment]
Ok, that one exists (returns redirect to `https://worldofwarships.eu/`). Maybe I didn't see it because my sandbox expired before the game was fully installed. Let me try a longer one and report back

**Comment by iam-py-test** [comment]
I don't see any problems with the downloaded file, so unless Imre objects, I am merging this PR

**Comment by DandelionSprout** [comment]
I'm in poor shape this week, so you can merge these kinds of PRs as you see fit.

**Comment by iam-py-test** [comment]
> I'm in poor shape this week, so you can merge these kinds of PRs as you see fit.

Ok. Hope you get better

**Pull request merged**
