### PR TITLE
Adding mastodon.top domain in safe list

### PR DESCRIPTION
**Pull request by kyriog**

### CODE REVIEW

**Comment by iam-py-test** [comment]
For reference:
[1/90 on VirusTotal](https://www.virustotal.com/gui/url/500674650359d66726faa89e8a1303cf1e8d540f48376574b9d39d085c3dac73). The _Quttera_ detection appears to be a false positive as zpr[.]io is a URL shortener which somebody posted a link to in October. The link posted is dead.
It has a grade A+ on HTTPS, and is registered with Namecheap.

**Comment by DandelionSprout** [comment]
It seems to be a comparatively big Mastodon instance (Perhaps a few thousand users, out of the circa 60,000 weekly Mastodon users across all instances), so it seems safe enough to me. I'll whitelist it in Google Android and DuckDuckGo search results too, and will then merge it.

**Comment by iam-py-test** [comment]
@DandelionSprout FYI, data-domain doesn't work anymore for DuckDuckGo.
I have been using `duckduckgo.com,3g2upl4pq6kufc4m.onion,duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion##[data-nrn="result"]:has(a[href*="://domain"])`, but no idea if that's the best solution

**Comment by DandelionSprout** [comment]
I'll look into it within a couple days.

**Pull request merged**
