### PR TITLE
Add some malware domains from my lists

### PR DESCRIPTION
**Pull request by iam-py-test**
This adds some domains from my blocklists to the antimalware list.
Please tell me if the format is wrong & I can fix it

### CODE REVIEW

**Comment by DandelionSprout** [comment]
I feel there must be a better option regarding all the references. For instance, I don't think `||45.90.58.90^$doc` warrant 5 in-list references for it. If those references had been cut by 50% through any way or approach, I'd approve them.

On a smaller note, I feel `||tinyurl.com/gp84uz2$doc` needs either a `^` or `|` before the `$doc`

**Comment by iam-py-test** [comment]
@DandelionSprout I have reduced the unneeded references and corrected the syntax

**Comment by DandelionSprout** [comment]
I hereby give this my approval now. All you need to do now is to replace the `! (Will add PR link later)` line, and me and/or you can merge this.

**Comment by iam-py-test** [comment]
> 
> 
> I hereby give this my approval now. All you need to do now is to replace the `! (Will add PR link later)` line, and me and/or you can merge this.

Somehow I forgot to remove that.
Thanks for pointing it out

**Pull request merged**
